site_name: Wave wet en regelgeving

theme:
  name: material
  langueage: en
  logo: logo.png
  favicon: favicon.png
 
# Copyright
copyright: Copyright © 2024 Wave Testserver

site_url: https://apvtest.wavetestserver.nl

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Keybinds: keybinds.md
  - Voertuigenlijst: voertuigenlijst.md
  - Wapens & Items: weapon-items.md
